name: Test
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Unittest
        run: |
          make test
