on:
  push:
    tags:
      - '*'

name: Build framework
jobs:
  static:
    name: Build static SDK
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd SwaarmSdk

          xcodebuild -target SwaarmSdk -configuration Release clean build

          mkdir SwaarmSdkStatic
          mv build/Release-iphoneos/* SwaarmSdkStatic 

          cd SwaarmSdkStatic
          zip -ry ../../SwaarmSdk.framework.zip *

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: static_framework
          path: SwaarmSdk.framework.zip

  release:
    name: Create new release and upload assets
    runs-on: ubuntu-latest
    needs: [static]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Download all frameworks
        uses: actions/download-artifact@v2
        with:
          path: frameworks
          
      - name: Upload static framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/static_framework/SwaarmSdk.framework.zip
          asset_name: SwaarmSdk.framework.zip
          asset_content_type: application/zip
          

